name: chat_dependencies
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: 3.0.5

dependencies:
  flutter:
    sdk: flutter

  flutter_triple: ^1.2.7+4
  flutter_modular: ^5.0.3
  fpdart: ^0.2.0

  ###
  # Linter
  ###
  very_good_analysis: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
