name: chat_ui
description: A new Flutter package project.
version: 0.0.1
publish_to: "none"
homepage:

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: 3.0.5

dependencies:
  flutter:
    sdk: flutter

    
  chat_dependencies:
    path: ../chat_dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
