name: Core - CI
"on":
  pull_request:
    branches: 
      - dev
    paths:
      - 'chat_core/**'
    
jobs:
  core-ci:
    runs-on: ubuntu-latest
    env: 
      working-directory: ./chat_core
    
    steps:
      - uses: actions/checkout@v2
      - name: Install Flutter
        uses: subosito/flutter-action@v2.2.1 
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
        working-directory: '${{ env.working-directory }}'
      - name: Run analyzes
        run: flutter analyze
        working-directory: '${{ env.working-directory }}'
      - name: Run test
        run: flutter test
        working-directory: '${{ env.working-directory }}'